name: build
on:
  workflow_call:
    inputs:
      testArtifactName:
        description: no description for this artifact
        required: false
        type: string
    secrets:
      MONGODB_DB_USERNAME:
    outputs:
      result:
        description:
        value: ${{jobs.deployment.outputs.ArtifactsFiles}}

jobs:
  deployment:
    runs-on: ubuntu-latest
    outputs:
      ArtifactsFiles: ${{steps.artifactFiles.outputs.ArtifactsFiles}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.2

      - name: Caching Dependencies
        id: cache
        uses: actions/cache@v1.2.1
        with:
          path: node_modules
          key: node-modules-cache-dependencies-${{hashFiles('**/package-lock.json')}}

      - name: Installing Dependencies
        if: ${{steps.cache.outputs.cache-hit != 'true'}}
        run: npm ci

      - name: Downloading Artifacts
        uses: actions/download-artifact@v2.1.1
        with:
          name: ${{ inputs.testArtifactName }}

      - name: Building
        run: npm run build

      - name: Upload Build Files
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build_files
          path: dist

      - name: Printing the contents of the Artifacts
        id: artifactFiles
        run: |
          ls
          echo "::set-output name=ArtifactsFiles:: These are the build files"

      - name: Printing Secrets
        run: echo "${{secrets.MONGODB_DB_USERNAME}}"
