# Name of Workflow
name: Testing

# Giving the event on which the workflow will be triggered
on: 
  workflow_dispatch:

  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

    types:
      - opened
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.2

      - name: Caching Dependencies
        id: cache
        uses: actions/cache@v1.2.1
        with:
          path: node_modules
          key: node-modules-cache-dependencies-${{hashFiles('**/package-lock.json')}}

      - name: Installing Dependencies
        if: ${{steps.cache.outputs.cache-hit != 'true'}}
        run: npm ci
      
      - name: Running Tests
        id: running-tests
        run: npm run test

      - name: Upload Test Report
        if: ${{failure() && steps.running-tests.outcome == 'failure'}}
        uses:  actions/upload-artifact@v3.1.2
        with:
          name: test-reprt
          path: test.json
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3.5.2

      - name: Caching Dependencies
        id: cache
        uses: actions/cache@v1.2.1
        with:
          path: node_modules
          key: node-modules-cache-dependencies-${{hashFiles('**/package-lock.json')}}

      - name: Installing Dependencies
        if: ${{steps.cache.outputs.cache-hit != 'true'}}
        run: npm ci
    
      - name: Building
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3.5.2

      - name: Caching Dependencies
        id: cache
        uses: actions/cache@v1.2.1
        with:
          path: node_modules
          key: node-modules-cache-dependencies-${{hashFiles('**/package-lock.json')}}

      - name: Installing Dependencies
        if: ${{steps.cache.outputs.cache-hit != 'true'}}
        run: npm ci
    
      - name: linting
        run: npm run lint

  deploying:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.2

      - name: Caching Dependencies
        id: cache
        uses: actions/cache@v1.2.1
        with:
          path: node_modules
          key: node-modules-cache-dependencies-${{hashFiles('**/package-lock.json')}}

      - name: Installing Dependencies
        if: ${{steps.cache.outputs.cache-hit != 'true'}}
        run: npm ci
  
      - name: Deployment
        run: echo 'The Application has been deployed Successfully'
  
  FailedResults:
    runs-on: ubuntu-latest
    needs: [deploying, lint]
    if: ${{failure()}}
    steps:
      - name: Printing Tests Resultes
        run: echo 'Testing Failed'

  PassedResults:
    runs-on: ubuntu-latest
    needs: [deploying, lint]
    if: ${{success()}}
    steps:
      - name: Printing Tests Resultes
        run: echo 'Testing Successful'